- platform: buienradar
  monitored_conditions:
#     - symbol
#     - humidity
#     - temperature
#     - windspeed
#      current condition:
#     - condition
#     - conditioncode
#     - conditiondetailed
#     - conditionexact
#     - symbol
#     - symbol_1d
#     - symbol_2d
#     - symbol_3d
#     - symbol_4d
#     - symbol_5d
#     - temperature_1d
#     - temperature_2d
#     - temperature_3d
#     - temperature_4d
#     - temperature_5d
#     - rainchance_1d
#     - rainchance_2d
#     - rainchance_3d
#     - rainchance_4d
#     - rainchance_5d
#     - sunchance_1d
#     - sunchance_2d
#     - sunchance_3d
#     - sunchance_4d
#     - sunchance_5d
#     - rain_1d
#     - rain_4d
#     - rain_2d
#     - rain_3d
     - rain_5d
#     - precipitation
#     - precipitation_forecast_average
#     - precipitation_forecast_total
#
- id: Waze travel 01
  platform: waze_travel_time
  name: reistijd
  origin: device_tracker.yourdevice
  destination: zone.home
  region: 'EU'